import type { Template } from "./types";

// Pre-built templates users can add to their world.
// Each template ships with a rich, opinionated set of fields so a freshly
// added category is immediately useful — no manual setup required.
// IDs use a `lib_` prefix and get re-mapped at insertion time.
export const TEMPLATE_LIBRARY: (Template & { description: string; category: string })[] = [
  {
    id: "lib_character", name: "Personagens", icon: "User", color: "#e0a96d",
    category: "Pessoas", description: "Heróis, vilões e figurantes do seu mundo.",
    fields: [
      { id: "f1", name: "Retrato", type: "image" },
      { id: "f2", name: "Função", type: "text" },
      { id: "f3", name: "Título / Epíteto", type: "text" },
      { id: "f4", name: "Idade", type: "number" },
      { id: "f5", name: "Gênero", type: "select", options: ["Masculino","Feminino","Não-binário","Outro","Desconhecido"] },
      { id: "f6", name: "Raça", type: "text" },
      { id: "f7", name: "Classe / Profissão", type: "text" },
      { id: "f8", name: "Alinhamento", type: "select", options: ["Leal e Bom","Neutro Bom","Caótico Bom","Leal Neutro","Neutro","Caótico Neutro","Leal Mau","Neutro Mau","Caótico Mau"] },
      { id: "f9", name: "Vivo", type: "boolean" },
      { id: "f10", name: "Nascimento", type: "date" },
      { id: "f11", name: "Local de Nascimento", type: "text" },
      { id: "f12", name: "Altura", type: "text" },
      { id: "f13", name: "Aparência", type: "richtext" },
      { id: "f14", name: "Personalidade", type: "richtext" },
      { id: "f15", name: "Habilidades", type: "richtext" },
      { id: "f16", name: "Objetivos", type: "richtext" },
      { id: "f17", name: "Biografia", type: "richtext" },
      { id: "f18", name: "Relacionamentos", type: "relationship", multi: true },
    ],
  },
  {
    id: "lib_location", name: "Locais", icon: "MapPin", color: "#7dd3c0",
    category: "Geografia", description: "Cidades, regiões, ruínas e pontos de interesse.",
    fields: [
      { id: "f1", name: "Imagem", type: "image" },
      { id: "f2", name: "Tipo", type: "select", options: ["Cidade","Vilarejo","Reino","Continente","Floresta","Ruína","Masmorra","Montanha","Deserto","Ilha","Plano"] },
      { id: "f3", name: "Região", type: "text" },
      { id: "f4", name: "Clima", type: "select", options: ["Tropical","Temperado","Árido","Frio","Mágico","Variado"] },
      { id: "f5", name: "Terreno", type: "text" },
      { id: "f6", name: "População", type: "number" },
      { id: "f7", name: "Governo", type: "text" },
      { id: "f8", name: "Fundado em", type: "date" },
      { id: "f9", name: "Pontos de Interesse", type: "richtext" },
      { id: "f10", name: "História", type: "richtext" },
      { id: "f11", name: "Habitantes Notáveis", type: "relationship", multi: true },
      { id: "f12", name: "Descrição", type: "richtext" },
    ],
  },
  {
    id: "lib_faction", name: "Facções", icon: "Shield", color: "#f87171",
    category: "Sociedade", description: "Guildas, ordens, sindicatos e cultos.",
    fields: [
      { id: "f1", name: "Símbolo", type: "image" },
      { id: "f2", name: "Tipo", type: "select", options: ["Guilda","Ordem","Culto","Governo","Família","Mercenários","Rebelião","Sindicato"] },
      { id: "f3", name: "Líder", type: "relationship" },
      { id: "f4", name: "Sede", type: "relationship" },
      { id: "f5", name: "Tamanho", type: "select", options: ["Minúscula","Pequena","Média","Grande","Vasta"] },
      { id: "f6", name: "Influência", type: "select", options: ["Local","Regional","Nacional","Continental","Mundial"] },
      { id: "f7", name: "Ideologia", type: "richtext" },
      { id: "f8", name: "Objetivos", type: "richtext" },
      { id: "f9", name: "Aliados", type: "relationship", multi: true },
      { id: "f10", name: "Inimigos", type: "relationship", multi: true },
      { id: "f11", name: "Fundação", type: "date" },
      { id: "f12", name: "História", type: "richtext" },
    ],
  },
  {
    id: "lib_magic", name: "Sistemas de Magia", icon: "Sparkles", color: "#a78bfa",
    category: "Sobrenatural", description: "Regras de magia, fontes e custos.",
    fields: [
      { id: "f1", name: "Fonte", type: "text" },
      { id: "f2", name: "Custo", type: "text" },
      { id: "f3", name: "Limites", type: "richtext" },
      { id: "f4", name: "Praticantes", type: "text" },
      { id: "f5", name: "Raridade", type: "select", options: ["Comum","Incomum","Rara","Lendária"] },
      { id: "f6", name: "Regras", type: "richtext" },
      { id: "f7", name: "História", type: "richtext" },
    ],
  },
  {
    id: "lib_item", name: "Itens", icon: "Gem", color: "#fbbf24",
    category: "Objetos", description: "Equipamentos, relíquias e artefatos.",
    fields: [
      { id: "f1", name: "Imagem", type: "image" },
      { id: "f2", name: "Raridade", type: "select", options: ["Comum","Incomum","Raro","Épico","Lendário","Artefato"] },
      { id: "f3", name: "Tipo", type: "select", options: ["Arma","Armadura","Poção","Pergaminho","Relíquia","Ferramenta","Joia","Consumível"] },
      { id: "f4", name: "Mágico", type: "boolean" },
      { id: "f5", name: "Peso", type: "text" },
      { id: "f6", name: "Valor", type: "number" },
      { id: "f7", name: "Dano / Efeito", type: "text" },
      { id: "f8", name: "Proprietário Atual", type: "relationship" },
      { id: "f9", name: "Origem", type: "richtext" },
      { id: "f10", name: "Descrição", type: "richtext" },
    ],
  },
  {
    id: "lib_creature", name: "Criaturas", icon: "Skull", color: "#94a3b8",
    category: "Bestiário", description: "Monstros, animais e abominações.",
    fields: [
      { id: "f1", name: "Imagem", type: "image" },
      { id: "f2", name: "Tipo", type: "select", options: ["Besta","Aberração","Morto-vivo","Elemental","Fada","Demônio","Celestial","Dragão","Construto","Humanóide"] },
      { id: "f3", name: "Tamanho", type: "select", options: ["Minúsculo","Pequeno","Médio","Grande","Enorme","Colossal"] },
      { id: "f4", name: "Habitat", type: "text" },
      { id: "f5", name: "Dieta", type: "select", options: ["Herbívoro","Carnívoro","Onívoro","Mágico","Nenhum"] },
      { id: "f6", name: "Nível de Ameaça", type: "number" },
      { id: "f7", name: "Habilidades", type: "richtext" },
      { id: "f8", name: "Fraquezas", type: "richtext" },
      { id: "f9", name: "Comportamento", type: "richtext" },
      { id: "f10", name: "Lore", type: "richtext" },
    ],
  },
  {
    id: "lib_race", name: "Raças", icon: "Users", color: "#34d399",
    category: "Pessoas", description: "Povos e espécies inteligentes.",
    fields: [
      { id: "f1", name: "Imagem", type: "image" },
      { id: "f2", name: "Origem", type: "text" },
      { id: "f3", name: "Expectativa de Vida", type: "number" },
      { id: "f4", name: "Altura Média", type: "text" },
      { id: "f5", name: "Traços Físicos", type: "richtext" },
      { id: "f6", name: "Habilidades Inatas", type: "richtext" },
      { id: "f7", name: "Cultura", type: "richtext" },
      { id: "f8", name: "Idiomas", type: "text" },
      { id: "f9", name: "Territórios", type: "relationship", multi: true },
    ],
  },
  {
    id: "lib_religion", name: "Religiões", icon: "Flame", color: "#fb923c",
    category: "Sociedade", description: "Panteões, doutrinas e cultos religiosos.",
    fields: [
      { id: "f1", name: "Símbolo", type: "image" },
      { id: "f2", name: "Divindade Principal", type: "relationship" },
      { id: "f3", name: "Panteão", type: "text" },
      { id: "f4", name: "Tipo", type: "select", options: ["Monoteísta","Politeísta","Animista","Ancestral","Filosófica","Culto"] },
      { id: "f5", name: "Seguidores", type: "number" },
      { id: "f6", name: "Templos", type: "relationship", multi: true },
      { id: "f7", name: "Crenças", type: "richtext" },
      { id: "f8", name: "Ritos", type: "richtext" },
      { id: "f9", name: "História", type: "richtext" },
    ],
  },
  {
    id: "lib_event", name: "Eventos Históricos", icon: "Scroll", color: "#c084fc",
    category: "História", description: "Guerras, descobertas e marcos do mundo.",
    fields: [
      { id: "f1", name: "Data", type: "date" },
      { id: "f2", name: "Era", type: "text" },
      { id: "f3", name: "Local", type: "relationship" },
      { id: "f4", name: "Participantes", type: "relationship", multi: true },
      { id: "f5", name: "Tipo", type: "select", options: ["Guerra","Tratado","Descoberta","Catástrofe","Coroação","Profecia","Outro"] },
      { id: "f6", name: "Consequências", type: "richtext" },
      { id: "f7", name: "Resumo", type: "richtext" },
    ],
  },
  {
    id: "lib_language", name: "Idiomas", icon: "BookOpen", color: "#60a5fa",
    category: "Cultura", description: "Línguas faladas, escritas e mortas.",
    fields: [
      { id: "f1", name: "Família Linguística", type: "text" },
      { id: "f2", name: "Falantes", type: "number" },
      { id: "f3", name: "Status", type: "select", options: ["Viva","Morta","Litúrgica","Secreta","Constructo"] },
      { id: "f4", name: "Alfabeto", type: "text" },
      { id: "f5", name: "Regiões", type: "relationship", multi: true },
      { id: "f6", name: "Gramática", type: "richtext" },
      { id: "f7", name: "Exemplo", type: "richtext" },
    ],
  },
  {
    id: "lib_quest", name: "Missões", icon: "Compass", color: "#facc15",
    category: "Campanha", description: "Aventuras e arcos narrativos.",
    fields: [
      { id: "f1", name: "Tipo", type: "select", options: ["Principal","Secundária","Diária","Pessoal"] },
      { id: "f2", name: "Status", type: "select", options: ["Não Iniciada","Em Andamento","Concluída","Falhada"] },
      { id: "f3", name: "Dificuldade", type: "select", options: ["Trivial","Fácil","Média","Difícil","Mortal"] },
      { id: "f4", name: "Cliente", type: "relationship" },
      { id: "f5", name: "Local", type: "relationship" },
      { id: "f6", name: "Recompensa", type: "text" },
      { id: "f7", name: "Objetivos", type: "richtext" },
      { id: "f8", name: "Reviravoltas", type: "richtext" },
      { id: "f9", name: "Descrição", type: "richtext" },
    ],
  },
  {
    id: "lib_session", name: "Sessões de Jogo", icon: "Book", color: "#22d3ee",
    category: "Campanha", description: "Registros das sessões de RPG.",
    fields: [
      { id: "f1", name: "Data", type: "date" },
      { id: "f2", name: "Número da Sessão", type: "number" },
      { id: "f3", name: "Duração (h)", type: "number" },
      { id: "f4", name: "Jogadores Presentes", type: "relationship", multi: true },
      { id: "f5", name: "NPCs Encontrados", type: "relationship", multi: true },
      { id: "f6", name: "Locais Visitados", type: "relationship", multi: true },
      { id: "f7", name: "Recompensas", type: "richtext" },
      { id: "f8", name: "Resumo", type: "richtext" },
      { id: "f9", name: "Próximos Passos", type: "richtext" },
    ],
  },
  {
    id: "lib_organization", name: "Organizações", icon: "Crown", color: "#eab308" ,
    category: "Sociedade", description: "Empresas, conselhos e instituições.",
    fields: [
      { id: "f1", name: "Logo", type: "image" },
      { id: "f2", name: "Sede", type: "relationship" },
      { id: "f3", name: "Líder", type: "relationship" },
      { id: "f4", name: "Membros", type: "number" },
      { id: "f5", name: "Hierarquia", type: "richtext" },
      { id: "f6", name: "Propósito", type: "richtext" },
      { id: "f7", name: "Recursos", type: "richtext" },
    ],
  },
  {
    id: "lib_vehicle", name: "Veículos", icon: "Anchor", color: "#38bdf8",
    category: "Objetos", description: "Navios, montarias e máquinas de transporte.",
    fields: [
      { id: "f1", name: "Imagem", type: "image" },
      { id: "f2", name: "Tipo", type: "select", options: ["Marítimo","Terrestre","Aéreo","Mágico","Subterrâneo"] },
      { id: "f3", name: "Capacidade", type: "number" },
      { id: "f4", name: "Velocidade", type: "text" },
      { id: "f5", name: "Tripulação", type: "number" },
      { id: "f6", name: "Armamento", type: "richtext" },
      { id: "f7", name: "Proprietário", type: "relationship" },
      { id: "f8", name: "Descrição", type: "richtext" },
    ],
  },
  {
    id: "lib_deity", name: "Divindades", icon: "Star", color: "#f472b6",
    category: "Sobrenatural", description: "Deuses, demônios e seres divinos.",
    fields: [
      { id: "f1", name: "Símbolo", type: "image" },
      { id: "f2", name: "Domínio", type: "text" },
      { id: "f3", name: "Alinhamento", type: "select", options: ["Leal e Bom","Neutro Bom","Caótico Bom","Leal Neutro","Neutro","Caótico Neutro","Leal Mau","Neutro Mau","Caótico Mau"] },
      { id: "f4", name: "Panteão", type: "text" },
      { id: "f5", name: "Animal Sagrado", type: "text" },
      { id: "f6", name: "Arma Favorita", type: "text" },
      { id: "f7", name: "Seguidores", type: "relationship", multi: true },
      { id: "f8", name: "Mitos", type: "richtext" },
    ],
  },
  {
    id: "lib_plant", name: "Plantas", icon: "Trees", color: "#4ade80",
    category: "Bestiário", description: "Flora, ervas e fungos.",
    fields: [
      { id: "f1", name: "Imagem", type: "image" },
      { id: "f2", name: "Habitat", type: "text" },
      { id: "f3", name: "Raridade", type: "select", options: ["Comum","Incomum","Rara","Lendária"] },
      { id: "f4", name: "Comestível", type: "boolean" },
      { id: "f5", name: "Tóxica", type: "boolean" },
      { id: "f6", name: "Propriedades", type: "richtext" },
      { id: "f7", name: "Usos Alquímicos", type: "richtext" },
    ],
  },
  {
    id: "lib_culture", name: "Culturas", icon: "Feather", color: "#fde047",
    category: "Cultura", description: "Costumes, ritos e tradições.",
    fields: [
      { id: "f1", name: "Origem", type: "text" },
      { id: "f2", name: "Idiomas", type: "relationship", multi: true },
      { id: "f3", name: "Valores", type: "richtext" },
      { id: "f4", name: "Costumes", type: "richtext" },
      { id: "f5", name: "Festas", type: "richtext" },
      { id: "f6", name: "Vestimenta", type: "richtext" },
      { id: "f7", name: "Culinária", type: "richtext" },
    ],
  },
  {
    id: "lib_law", name: "Leis", icon: "Key", color: "#a3a3a3",
    category: "Sociedade", description: "Códigos legais e edits.",
    fields: [
      { id: "f1", name: "Jurisdição", type: "relationship" },
      { id: "f2", name: "Tipo", type: "select", options: ["Criminal","Civil","Religiosa","Comercial","Marcial"] },
      { id: "f3", name: "Severidade", type: "select", options: ["Branda","Moderada","Severa","Capital"] },
      { id: "f4", name: "Pena", type: "text" },
      { id: "f5", name: "Promulgada em", type: "date" },
      { id: "f6", name: "Texto", type: "richtext" },
    ],
  },
  {
    id: "lib_technology", name: "Tecnologias", icon: "Hexagon", color: "#06b6d4",
    category: "Cultura", description: "Invenções e descobertas técnicas.",
    fields: [
      { id: "f1", name: "Era", type: "text" },
      { id: "f2", name: "Inventor", type: "relationship" },
      { id: "f3", name: "Disponibilidade", type: "select", options: ["Protótipo","Rara","Comum","Universal","Perdida"] },
      { id: "f4", name: "Materiais", type: "text" },
      { id: "f5", name: "Funcionamento", type: "richtext" },
      { id: "f6", name: "Impacto Social", type: "richtext" },
    ],
  },
  {
    id: "lib_battle", name: "Batalhas", icon: "Sword", color: "#dc2626",
    category: "História", description: "Combates e conflitos militares.",
    fields: [
      { id: "f1", name: "Data", type: "date" },
      { id: "f2", name: "Local", type: "relationship" },
      { id: "f3", name: "Lado A", type: "relationship", multi: true },
      { id: "f4", name: "Lado B", type: "relationship", multi: true },
      { id: "f5", name: "Vencedor", type: "text" },
      { id: "f6", name: "Baixas", type: "number" },
      { id: "f7", name: "Comandantes", type: "relationship", multi: true },
      { id: "f8", name: "Táticas", type: "richtext" },
      { id: "f9", name: "Crônica", type: "richtext" },
    ],
  },
  {
    id: "lib_kingdom", name: "Reinos", icon: "Castle", color: "#9333ea",
    category: "Geografia", description: "Nações e impérios.",
    fields: [
      { id: "f1", name: "Bandeira", type: "image" },
      { id: "f2", name: "Capital", type: "relationship" },
      { id: "f3", name: "Governante", type: "relationship" },
      { id: "f4", name: "Forma de Governo", type: "select", options: ["Monarquia","República","Teocracia","Ditadura","Tribal","Conselho","Anarquia"] },
      { id: "f5", name: "População", type: "number" },
      { id: "f6", name: "Exército", type: "number" },
      { id: "f7", name: "Religião Oficial", type: "relationship" },
      { id: "f8", name: "Idioma Oficial", type: "relationship" },
      { id: "f9", name: "Aliados", type: "relationship", multi: true },
      { id: "f10", name: "Inimigos", type: "relationship", multi: true },
      { id: "f11", name: "História", type: "richtext" },
    ],
  },
  {
    id: "lib_class", name: "Classes", icon: "Sword", color: "#ef4444",
    category: "Mecânicas", description: "Classes de personagem jogáveis.",
    fields: [
      { id: "f1", name: "Dado de Vida", type: "text" },
      { id: "f2", name: "Atributo Principal", type: "text" },
      { id: "f3", name: "Proficiências", type: "richtext" },
      { id: "f4", name: "Equipamento Inicial", type: "richtext" },
      { id: "f5", name: "Habilidades de Nível", type: "richtext" },
      { id: "f6", name: "Subclasses", type: "richtext" },
      { id: "f7", name: "Descrição", type: "richtext" },
    ],
  },
  {
    id: "lib_spell", name: "Magias", icon: "Sparkles", color: "#8b5cf6",
    category: "Sobrenatural", description: "Feitiços, encantamentos e rituais.",
    fields: [
      { id: "f1", name: "Nível", type: "number" },
      { id: "f2", name: "Escola", type: "select", options: ["Abjuração","Adivinhação","Conjuração","Encantamento","Evocação","Ilusão","Necromancia","Transmutação"] },
      { id: "f3", name: "Tempo de Conjuração", type: "text" },
      { id: "f4", name: "Alcance", type: "text" },
      { id: "f5", name: "Duração", type: "text" },
      { id: "f6", name: "Componentes", type: "text" },
      { id: "f7", name: "Ritual", type: "boolean" },
      { id: "f8", name: "Classes", type: "relationship", multi: true },
      { id: "f9", name: "Efeito", type: "richtext" },
    ],
  },
  {
    id: "lib_relic", name: "Relíquias", icon: "Gem", color: "#d946ef",
    category: "Objetos", description: "Artefatos lendários e itens de poder.",
    fields: [
      { id: "f1", name: "Imagem", type: "image" },
      { id: "f2", name: "Idade", type: "text" },
      { id: "f3", name: "Criador", type: "relationship" },
      { id: "f4", name: "Localização Atual", type: "relationship" },
      { id: "f5", name: "Poderes", type: "richtext" },
      { id: "f6", name: "Maldição", type: "richtext" },
      { id: "f7", name: "Lenda", type: "richtext" },
      { id: "f8", name: "Origem", type: "richtext" },
    ],
  },
  {
    id: "lib_lore", name: "Lendas", icon: "Scroll", color: "#fcd34d",
    category: "História", description: "Mitos, rumores e contos.",
    fields: [
      { id: "f1", name: "Origem", type: "text" },
      { id: "f2", name: "Veracidade", type: "select", options: ["Mito","Lenda","Rumor","Histórico","Profecia"] },
      { id: "f3", name: "Personagens Citados", type: "relationship", multi: true },
      { id: "f4", name: "Locais Citados", type: "relationship", multi: true },
      { id: "f5", name: "Conteúdo", type: "richtext" },
    ],
  },
];

export const LIBRARY_CATEGORIES = Array.from(new Set(TEMPLATE_LIBRARY.map((t) => t.category)));

// ================================================================
// SCI-FI COLLECTION
// ================================================================
export const SCIFI_LIBRARY: (Template & { description: string; category: string })[] = [
  {
    id: "sf_character", name: "Personagens", icon: "User", color: "#38bdf8",
    category: "Tripulação", description: "Membros de tripulação, cientistas e ciborgues.",
    fields: [
      { id: "f1", name: "Retrato", type: "image" },
      { id: "f2", name: "Espécie", type: "text" },
      { id: "f3", name: "Patente", type: "text" },
      { id: "f4", name: "Facção", type: "relationship" },
      { id: "f5", name: "Implantes", type: "richtext" },
      { id: "f6", name: "Habilidades", type: "richtext" },
      { id: "f7", name: "Biografia", type: "richtext" },
    ],
  },
  {
    id: "sf_planet", name: "Planetas", icon: "Globe", color: "#8b5cf6",
    category: "Astronomia", description: "Mundos habitáveis, colônias e planetas alienígenas.",
    fields: [
      { id: "f1", name: "Imagem", type: "image" },
      { id: "f2", name: "Sistema Estelar", type: "text" },
      { id: "f3", name: "Gravidade", type: "text" },
      { id: "f4", name: "Atmosfera", type: "text" },
      { id: "f5", name: "Habitável", type: "boolean" },
      { id: "f6", name: "População", type: "number" },
      { id: "f7", name: "Governo", type: "text" },
      { id: "f8", name: "Recursos", type: "richtext" },
      { id: "f9", name: "História", type: "richtext" },
    ],
  },
  {
    id: "sf_ship", name: "Naves", icon: "Anchor", color: "#22d3ee",
    category: "Frota", description: "Naves espaciais e estações orbitais.",
    fields: [
      { id: "f1", name: "Imagem", type: "image" },
      { id: "f2", name: "Classe", type: "text" },
      { id: "f3", name: "Comprimento", type: "text" },
      { id: "f4", name: "Tripulação", type: "number" },
      { id: "f5", name: "Armamento", type: "richtext" },
      { id: "f6", name: "Motor", type: "text" },
      { id: "f7", name: "Capitão", type: "relationship" },
      { id: "f8", name: "Facção", type: "relationship" },
    ],
  },
  {
    id: "sf_alien", name: "Espécies Alienígenas", icon: "Skull", color: "#4ade80",
    category: "Xenobiologia", description: "Formas de vida extraterrestre.",
    fields: [
      { id: "f1", name: "Imagem", type: "image" },
      { id: "f2", name: "Planeta Natal", type: "relationship" },
      { id: "f3", name: "Nível Tecnológico", type: "select", options: ["Pré-industrial","Industrial","Espacial","Interestelar","Transcendente"] },
      { id: "f4", name: "Fisiologia", type: "richtext" },
      { id: "f5", name: "Sociedade", type: "richtext" },
      { id: "f6", name: "Diplomacia", type: "richtext" },
    ],
  },
  {
    id: "sf_tech", name: "Tecnologias", icon: "Sparkles", color: "#facc15",
    category: "Ciência", description: "Invenções, dispositivos e ciência avançada.",
    fields: [
      { id: "f1", name: "Categoria", type: "select", options: ["Armamento","Propulsão","Comunicação","Médica","Cibernética","IA","Terraformação"] },
      { id: "f2", name: "Inventor", type: "relationship" },
      { id: "f3", name: "Disponibilidade", type: "select", options: ["Protótipo","Militar","Corporativa","Civil","Proibida"] },
      { id: "f4", name: "Descrição", type: "richtext" },
      { id: "f5", name: "Impacto", type: "richtext" },
    ],
  },
  {
    id: "sf_faction", name: "Corporações", icon: "Shield", color: "#f472b6",
    category: "Poder", description: "Megacorporações, impérios e sindicatos.",
    fields: [
      { id: "f1", name: "Logo", type: "image" },
      { id: "f2", name: "Setor", type: "text" },
      { id: "f3", name: "CEO / Líder", type: "relationship" },
      { id: "f4", name: "Sede", type: "relationship" },
      { id: "f5", name: "Influência", type: "select", options: ["Local","Planetária","Sistêmica","Interestelar","Galáctica"] },
      { id: "f6", name: "História", type: "richtext" },
    ],
  },
  {
    id: "sf_mission", name: "Missões", icon: "Compass", color: "#fb923c",
    category: "Operações", description: "Contratos, operações e exploração.",
    fields: [
      { id: "f1", name: "Cliente", type: "relationship" },
      { id: "f2", name: "Recompensa", type: "text" },
      { id: "f3", name: "Nível de Risco", type: "select", options: ["Baixo","Médio","Alto","Extremo","Suicida"] },
      { id: "f4", name: "Status", type: "select", options: ["Disponível","Em Andamento","Concluída","Falhada"] },
      { id: "f5", name: "Objetivos", type: "richtext" },
      { id: "f6", name: "Briefing", type: "richtext" },
    ],
  },
];

// ================================================================
// MODERN / URBAN COLLECTION
// ================================================================
export const MODERN_LIBRARY: (Template & { description: string; category: string })[] = [
  {
    id: "md_character", name: "Personagens", icon: "User", color: "#f87171",
    category: "Elenco", description: "Protagonistas, contatos e alvos.",
    fields: [
      { id: "f1", name: "Foto", type: "image" },
      { id: "f2", name: "Idade", type: "number" },
      { id: "f3", name: "Ocupação", type: "text" },
      { id: "f4", name: "Nacionalidade", type: "text" },
      { id: "f5", name: "Telefone", type: "text" },
      { id: "f6", name: "Endereço", type: "text" },
      { id: "f7", name: "Perfil Psicológico", type: "richtext" },
      { id: "f8", name: "Histórico", type: "richtext" },
      { id: "f9", name: "Contatos", type: "relationship", multi: true },
    ],
  },
  {
    id: "md_location", name: "Locais", icon: "MapPin", color: "#a78bfa",
    category: "Cenários", description: "Cidades, prédios e pontos de encontro.",
    fields: [
      { id: "f1", name: "Foto", type: "image" },
      { id: "f2", name: "Endereço", type: "text" },
      { id: "f3", name: "Cidade", type: "text" },
      { id: "f4", name: "País", type: "text" },
      { id: "f5", name: "Tipo", type: "select", options: ["Residencial","Comercial","Industrial","Governamental","Público","Secreto"] },
      { id: "f6", name: "Descrição", type: "richtext" },
    ],
  },
  {
    id: "md_organization", name: "Organizações", icon: "Crown", color: "#facc15",
    category: "Poder", description: "Empresas, agências e grupos criminosos.",
    fields: [
      { id: "f1", name: "Logo", type: "image" },
      { id: "f2", name: "Tipo", type: "select", options: ["Empresa","Agência","Máfia","ONG","Culto","Governo"] },
      { id: "f3", name: "Líder", type: "relationship" },
      { id: "f4", name: "Sede", type: "relationship" },
      { id: "f5", name: "Legalidade", type: "select", options: ["Legal","Cinza","Ilegal"] },
      { id: "f6", name: "Descrição", type: "richtext" },
    ],
  },
  {
    id: "md_case", name: "Casos", icon: "Scroll", color: "#22d3ee",
    category: "Investigação", description: "Investigações, crimes e mistérios.",
    fields: [
      { id: "f1", name: "Data", type: "date" },
      { id: "f2", name: "Status", type: "select", options: ["Aberto","Em Andamento","Encerrado","Arquivado"] },
      { id: "f3", name: "Local", type: "relationship" },
      { id: "f4", name: "Envolvidos", type: "relationship", multi: true },
      { id: "f5", name: "Evidências", type: "richtext" },
      { id: "f6", name: "Notas", type: "richtext" },
    ],
  },
  {
    id: "md_item", name: "Itens & Equipamentos", icon: "Gem", color: "#4ade80",
    category: "Recursos", description: "Armas, veículos e gadgets.",
    fields: [
      { id: "f1", name: "Foto", type: "image" },
      { id: "f2", name: "Categoria", type: "select", options: ["Arma","Veículo","Gadget","Documento","Droga","Outros"] },
      { id: "f3", name: "Proprietário", type: "relationship" },
      { id: "f4", name: "Valor", type: "number" },
      { id: "f5", name: "Descrição", type: "richtext" },
    ],
  },
  {
    id: "md_event", name: "Eventos", icon: "Clock", color: "#fb923c",
    category: "Cronologia", description: "Acontecimentos, encontros e reuniões.",
    fields: [
      { id: "f1", name: "Data", type: "date" },
      { id: "f2", name: "Local", type: "relationship" },
      { id: "f3", name: "Participantes", type: "relationship", multi: true },
      { id: "f4", name: "Resumo", type: "richtext" },
    ],
  },
];

export type LibraryTemplate = Template & { description: string; category: string };

export const TEMPLATE_COLLECTIONS: { id: string; name: string; description: string; templates: LibraryTemplate[] }[] = [
  { id: "fantasy", name: "Fantasia & RPG", description: "Personagens, magia, reinos e criaturas para mundos de fantasia clássica.", templates: TEMPLATE_LIBRARY as LibraryTemplate[] },
  { id: "scifi", name: "Ficção Científica", description: "Naves, planetas, alienígenas e alta tecnologia para universos de sci-fi.", templates: SCIFI_LIBRARY },
  { id: "modern", name: "Moderno / Urbano", description: "Personagens, casos e cenários para histórias contemporâneas ou noir.", templates: MODERN_LIBRARY },
];